# Generated by Django 3.0.8 on 2020-08-01 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamId',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('exam_id', models.IntegerField()),
                ('player_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='exam_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.Exams'),
        ),
    ]
